name: Government Official epaper Generation Workflow

on:
  schedule:
   - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  generate-government-official-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Main Script
        env:
          GOVERNMENT_OFFICIAL_NEWS_SOURCE_URL: ${{ secrets.GOVERNMENT_OFFICIAL_NEWS_SOURCE_URL }} 
          GOVERNMENT_OFFICIAL_NEWS_EVENT_SUBSCRIBER_URL: ${{ secrets.GOVERNMENT_OFFICIAL_NEWS_EVENT_SUBSCRIBER_URL }} 
          GOVERNMENT_OFFICIAL_NEWS_FEED_SYNOPSIS_GENERATOR_LLM_API_KEY: ${{ secrets.GOVERNMENT_OFFICIAL_NEWS_FEED_SYNOPSIS_GENERATOR_LLM_API_KEY }}
        run: |
          python main.py
        
      - name: Upload PDF Artifact 
        id: upload-step
        uses: actions/upload-artifact@v7
        with:
          name: GovernmentOfficialNewsLetter.pdf
          path: ./out/output.pdf
          if-no-files-found: error
        
      - name: Publish Event
        env:
          GOVERNMENT_OFFICIAL_NEWS_FEED_ARTIFACT_URL: https://release.tapri.dev/?download_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-step.outputs.artifact-id }}
          GOVERNMENT_OFFICIAL_NEWS_EVENT_SUBSCRIBER_URL: ${{ secrets.GOVERNMENT_OFFICIAL_NEWS_EVENT_SUBSCRIBER_URL }}
        run: |
          export GOVERNMENT_OFFICIAL_NEWS_FEED_SUMMARY="$(cat ./out/llm_output.md)"
          python discord/GovernmentOfficialNewsFeedEventPublisher.py 

      - name: Generate Job Summary
        run: |
            cat ./out/llm_output.md >> $GITHUB_STEP_SUMMARY